config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
  devise_for :users, module: :users

  resources :users, only: [] do
    collection do
      get 'profile(/:user_id)', to: 'users#profile', as: :profile
    end
  end
  resources :categories
  resources :posts do
    member do
      patch 'mark_as_accepted_comment/:comment_id', to: "posts#mark_as_accepted_comment", as: :mark_as_accepted
    end
    resources :comments
    resources :votes, only: [] do
      collection do
        patch 'toggle_upvote'
        patch 'toggle_downvote'
      end
    end
  end

  resources :comments, only: [] do
    resources :votes, only: [] do
      collection do
        patch 'toggle_upvote'
        patch 'toggle_downvote'
      end
    end
  end

  resources :notifications, only: %i[index destroy] do
    member do
      get 'mark_as_read'
    end
  end

  resources :supports

  post '/', to: 'pages#home'

  get 'user_policies', to: 'pages#user_policies', as: :user_policies
  get 'faq', to: 'pages#faq', as: :faq
  get 'support_page', to: 'pages#support_page', as: :support_page
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Votable

  belongs_to :user
  belongs_to :post

  has_rich_text :content
  has_one_attached :file

  validates :file, file: true
  validates :content, presence: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  before_action :set_comment, only: %i[ show edit update destroy ]
  before_action :set_post

  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user

    respond_to do |format|
      if @comment.save
        @post.increment!(:total_comments)
        if @post.notify_by_email && @post.user != current_user
          PostUserMailer.notify_user_for_new_comment_on_post(current_user, @comment).deliver_later
        end
        if @post.user != current_user
          Notification.create!(
            user: @post.user,
            title: "#{current_user.full_name} commented on your post",
            content: @comment.content.to_plain_text.truncate(10),
            link: post_path(@post)
          )
        end
        format.html { redirect_to post_path(@post), notice: "Comment was successfully created." }
        format.json { render :show, status: :created, location: @comment }
      else
        @comments = @post.comments.includes(:user, :votes).with_rich_text_content
        format.html { render 'posts/show', status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to post_path(@comment.post), notice: "Comment was successfully updated." }
        format.json { render :show, status: :ok, location: @comment }
      else
        @comments = @post.comments.includes(:user, :votes).with_rich_text_content
        format.html { render 'posts/show', status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @comment.destroy!

    respond_to do |format|
      @post.decrement!(:total_comments)
      format.html { redirect_to post_path(@post), notice: "Comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  def set_post
    @post = Post.find(params[:post_id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    params.require(:comment).permit(:content, :file)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="answer-body-wrap flex-grow-1">
  <div class="answer-body">
    <%= comment.content %>
    <%= file_preview(comment) %>
  </div><!-- end answer-body -->
  <div class="question-post-user-action">
    <div class="post-menu">
      <div class="btn-group">
        <button class="btn dropdown-toggle after-none" type="button" id="shareDropdownMenuTwo" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Share</button>
        <div class="dropdown-menu dropdown--menu dropdown--menu-2 mt-2" aria-labelledby="shareDropdownMenuTwo">
          <div class="py-3 px-4">
            <h4 class="fs-15 pb-2">Share a link to this question</h4>
            <form action="#" class="copy-to-clipboard">
              <span class="text-success-message">Link Copied!</span>
              <input type="text" class="form-control form--control form-control-sm copy-input" value="<%= post_url(@post) %>">
              <div class="btn-box pt-2 d-flex align-items-center justify-content-between">
                <a href="#" class="btn-text copy-btn">Copy link</a>
                <ul class="social-icons social-icons-sm">
                  <li><a href="#" class="bg-8 text-white shadow-none" title="Share link to this question on Facebook"><i class="la la-facebook"></i></a></li>
                  <li><a href="#" class="bg-9 text-white shadow-none" title="Share link to this question on Twitter"><i class="la la-twitter"></i></a></li>
                  <li><a href="#" class="bg-dark text-white shadow-none" title="Share link to this question on DEV"><i class="lab la-dev"></i></a></li>
                </ul>
              </div>
            </form>
          </div>
        </div>
      </div><!-- btn-group -->
<!--      <a href="#" class="btn">Edit</a>-->
      <% if can? :edit, comment %>
        <%= link_to 'Edit', post_path(@post, comment_id: comment.id), class: 'btn', data: { turbo: false } %>
      <% end %>

      <% if can? :destroy, comment %>
        <%= link_to 'Delete', post_comment_path(@post, comment), data: { turbo_confirm: 'Are you sure?', "turbo-method": :delete }, class: 'btn' %>
      <% end %>


    </div><!-- end post-menu -->
    <div class="media media-card user-media align-items-center">
      <%= link_to profile_users_path(comment.user), class: 'media-img d-block', data: { turbo: false } do %>
        <%= image_tag comment.user.avatar, alt: 'avatar' %>
      <% end %>

      <div class="media-body d-flex align-items-center justify-content-between">
        <div>
          <h5 class="pb-1">
            <%= link_to comment.user.full_name, profile_users_path(comment.user), data: { turbo: false }  %>
          </h5>
          <div class="stats fs-12 d-flex align-items-center lh-18">
            <%= user_badge(comment.user) %>
          </div>
        </div>
        <small class="meta d-block text-end">
          <span class="text-black d-block lh-18">answered</span>
          <span class="d-block lh-18 fs-12"><%= time_ago_in_words(comment.created_at) %> ago</span>
        </small>
      </div>
    </div><!-- end media -->

  </div><!-- end question-post-user-action -->
</div><!-- end answer-body-wrap -->

app/views/comments/_form.html.erb
<%= turbo_frame_tag @post, target: 'reload' do %>
<%= simple_form_for(@comment, url: @comment.new_record? ? post_comments_path(@post) : post_comment_path(@post, @comment), method: @comment.new_record? ? :post : :patch, data: { turbo: false }, html: { class: 'pt-3' }) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

<!--<form method="post" class="pt-3">-->
  <div class="input-box">
    <label class="fs-14 text-black lh-20 fw-medium">Body</label>
    <div class="form-group">
      <%= f.input_field :content, as: :text, class: 'form-control form--control form-control-sm fs-13 user-text-editor', rows: '6', placeholder: 'Your answer here...', value: f.object.content %>
<!--      <textarea class="form-control form--control form-control-sm fs-13 user-text-editor" name="message" rows="6" placeholder="Your answer here...">Your answer here...</textarea>-->
      <% if @comment.errors[:content] %>
        <div class="text-danger"><%= @comment.errors[:content].join %></div>
      <% end %>
    </div>
  </div>
  <div class="input-box">
    <label class="fs-14 text-black fw-medium">Image/File</label>
    <div class="form-group">
      <%= file_preview(@comment) %>
      <div class="file-upload-wrap file-upload-layout-2">
        <!--        <input type="file" name="files" class="file-upload-input">-->
        <%= f.input_field :file, class: 'file-upload-input', accept: 'text/plain, image/jpeg, image/png, application/pdf, application/msword, application/vnd.openxmlformats-officedocument.wordprocessingml.document' %>
        <% if @post.errors[:file] %>
          <div class="text-danger fs-14"><%= @post.errors[:file].join %></div>
        <% end %>
        <span class="file-upload-text d-flex align-items-center justify-content-center"><i class="la la-cloud-upload me-2 fs-24"></i>Drop files here or click to upload.</span>
      </div>
    </div>

  </div><!-- end input-box -->
<!--  <button class="btn theme-btn theme-btn-sm" type="submit">Post Your Answer</button>-->
  <% if user_signed_in? %>
  <%= f.button :submit, 'Post Your Answer', class: 'btn theme-btn theme-btn-sm', data: { target: '_top' } %>
  <% end %>
<!--</form>-->

<% end %>
<% end %>

<% unless user_signed_in? %>
<p class="text-black text-center fs-15">Already have an account?
  <%= link_to "Log in to leave a comment", new_user_session_path, class: 'text-color hover-underline' %>
</p>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<div class="answer-wrap d-flex">
  <div class="votes votes-styled w-auto">
    <div id="vote2" class="upvotejs">
      <a class="upvote upvote-on" data-bs-toggle="tooltip" data-placement="right" title="This question is useful"></a>
      <span class="count">2</span>
      <a class="downvote" data-bs-toggle="tooltip" data-placement="right" title="This question is not useful"></a>
      <a class="star check <%= @post.accepted_comment_id == comment.id ? 'star-on' : '' %>" data-bs-toggle="tooltip" data-placement="right" title="The question owner accepted this answer"></a>
    </div>
  </div><!-- end votes -->
  <div class="answer-body-wrap flex-grow-1">
    <%= render 'comments/comment', comment: %>
  </div><!-- end answer-body-wrap -->
</div><!-- end answer-wrap -->

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>