config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
  devise_for :users, module: :users

  resources :users, only: [] do
    collection do
      get 'profile(/:user_id)', to: 'users#profile', as: :profile
    end
  end
  resources :categories
  resources :posts do
    member do
      patch 'mark_as_accepted_comment/:comment_id', to: "posts#mark_as_accepted_comment", as: :mark_as_accepted
    end
    resources :comments
    resources :votes, only: [] do
      collection do
        patch 'toggle_upvote'
        patch 'toggle_downvote'
      end
    end
  end

  resources :comments, only: [] do
    resources :votes, only: [] do
      collection do
        patch 'toggle_upvote'
        patch 'toggle_downvote'
      end
    end
  end

  resources :notifications, only: %i[index destroy] do
    member do
      get 'mark_as_read'
    end
  end

  resources :supports

  post '/', to: 'pages#home'

  get 'user_policies', to: 'pages#user_policies', as: :user_policies
  get 'faq', to: 'pages#faq', as: :faq
  get 'support_page', to: 'pages#support_page', as: :support_page
end

app/models/post.rb
class Post < ApplicationRecord
  include Votable

  belongs_to :user
  belongs_to :category
  # has_many :votes, as: :votable, dependent: :destroy
  has_many :comments, dependent: :destroy
  # has_one :vote, -> (current_user) { where(user: current_user) }, as: :votable
  has_one :accepted_comment, class_name: 'Comment', primary_key: 'accepted_comment_id', dependent: :nullify
  has_one_attached :file
  validates :file, file: true

  has_rich_text :content
  has_one :action_text_rich_text, class_name: 'ActionText::RichText', as: :record
  attr_accessor :agree_terms

  # scope :toql_votes, -> { upvotes - downvotes }
  # scope :upvotes, -> { votes.where(upvote: true).count }
  # scope :downvotes, -> { votes.where(downvotes: true).count }

  validates :title, presence: true
  validates :content, presence: { message: "Can't be blank" }
  validate :profanity_filter
  validates :agree_terms, acceptance: true, presence: true, on: :create

  # def total_votes
  #   upvotes - downvotes
  # end
  #
  # def upvotes
  #   votes.where(upvote: true).count
  # end
  #
  # def downvotes
  #   votes.where(downvote: true).count
  # end

  # def total_comments
  #   comments.size
  # end

  def accepted_comment?(comment)
    accepted_comment_id == comment.id
  end

  def profanity_filter
    return unless title_changed? || self.attribute_changed?(:content)

    errors.add(:title, 'contains profanity') if ProfanityFilter.new.profane?(title)

    return unless ProfanityFilter.new.profane?(content.to_plain_text)

    errors.add(:content, 'contains profanity')
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  SORT_BY_OPTIONS = {
    'Active' => { updated_at: :desc },
    'Oldest' => { created_at: :desc },
    'Votes' => { total_upvotes: :desc },
  }.freeze

  before_action :authenticate_user!, except: %i[ index show ]

  load_and_authorize_resource

  before_action :set_post, only: %i[ show edit update destroy mark_as_accepted_comment]
  before_action :set_categories, only: %i[ new edit create update ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all.page(params[:page]).per(10)
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post.increment!(:views) if user_signed_in? && @post.user_id != current_user.id
    @comment = Comment.find_by(id: params[:comment_id]) || Comment.new
    sort_by = SORT_BY_OPTIONS[params[:sort_by]] || { created_at: :desc }
    @comments = @post.comments.order(sort_by).includes(:user, :votes).with_rich_text_content
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def mark_as_accepted_comment
    unless current_user == @post.user
      redirect_to post_path(@post), alert: 'You are not allowed to perform this action.' and return
    end

    @comment = @post.comments.find(params[:comment_id])

    if @post.accepted_comment?(@comment)
      @post.update(accepted_comment_id: nil)
    else
      @comment.user.increment_badge
      @post.update!(accepted_comment_id: @comment.id)

      Notification.create!(
        user: @comment.user,
        title: 'Your comment has been accepted as an answer',
        content: @comment.content.to_plain_text.truncate(10),
        link: post_path(@post)
      )
    end

    respond_to do |format|
      format.html { redirect_to post_path(@post) }
      format.json { render :show, status: :ok, location: @post }
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy!

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def set_categories
    @categories = Category.all.pluck(:name, :id)
  end

  # Only allow a list of trusted parameters through.
  def post_params
    custom_params = params.require(:post).permit(:title, :content, :tags, :category_id, :file, :agree_terms, :notify_by_email)
    custom_params[:tags] = custom_params[:tags].split(',').map(&:strip).uniq
    custom_params
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper # :nodoc:
  def last_active(post)
    "#{time_ago_in_words(@comments&.last&.created_at || post.created_at)} ago"
  end

  def total_questions
    number_to_human(Post.count)
  end

  def total_answers
    number_to_human Comment.count
  end

  def total_accepted_answers
    number_to_human Post.where.not(accepted_comment_id: nil).count
  end

  def total_users
    number_to_human User.count
  end

  def trending_tags
    @trending_tags ||= Post.from(Post.select('unnest(tags) as tag')).select('count(tag) total, tag').group('tag')
                           .order('total desc').limit(11)
  end

  def related_questions
    Post.order('RANDOM()').includes(:user).limit(3)
  end

  def file_preview(post)
    return unless post.file.attached?

    if post.file.representable?
      link_to rails_blob_path(post.file), target: '_blank' do
        image_tag post.file.representation(resize_to_limit: [100, 100])
      end
    else
      link_to 'Attachment', rails_blob_path(post.file, disposition: "attachment")
    end
  end
end

app/views/posts/partials/_comment.html.erb
<div class="answer-wrap d-flex">
  <div class="votes votes-styled w-auto">
    <%#= turbo_frame_tag comment do %>
      <div id="vote2" class="upvotejs">
        <%= link_to '', toggle_upvote_comment_votes_path(comment_id: comment.id), data: { 'turbo-method': :patch }, class: "upvote #{comment.upvoted?(current_user) ? 'upvote-on' : ''}", 'data-bs-toggle': 'tooltip', 'data-placement': 'right', title: 'This question is useful' %>
        <span class="count"><%= comment.total_votes %></span>
        <%= link_to '', toggle_downvote_comment_votes_path(comment_id: comment.id), data: { 'turbo-method': :patch }, class: "downvote #{comment.downvoted?(current_user) ? 'downvote-on' : ''}", 'data-bs-toggle': 'tooltip', 'data-placement': 'right', title: 'This question is not useful' %>
        <% if current_user == @post.user %>
          <%= link_to '', mark_as_accepted_post_path(@post, comment), data: { 'turbo-method': :patch, turbo_frame: 'comments' }, class: "star check #{@post.accepted_comment?(comment) ? 'star-on' : '' }", 'data-bs-toggle': 'tooltip', 'data-placement': 'right', title: "#{@post.accepted_comment?(comment) ? 'The question owner accepted this answer' : 'Mark as accepted answer'}" %>
        <% elsif @post.accepted_comment == comment %>
          <a class="star check star-on" data-bs-toggle="tooltip" data-placement="right" title="The question owner accepted this answer"></a>
        <% end %>
      </div>
    <%# end %>
  </div><!-- end votes -->
  <div class="answer-body-wrap flex-grow-1">
    <%= render 'comments/comment', comment: %>
  </div><!-- end answer-body-wrap -->
</div><!-- end answer-wrap -->

app/views/posts/partials/_hero_area.html.erb
<% unless user_signed_in? %>
  <!--======================================
          START HERO AREA
  ======================================-->
  <section class="hero-area bg-white shadow-sm overflow-hidden pt-40px pb-40px">
    <span class="stroke-shape stroke-shape-1"></span>
    <span class="stroke-shape stroke-shape-2"></span>
    <span class="stroke-shape stroke-shape-3"></span>
    <span class="stroke-shape stroke-shape-4"></span>
    <span class="stroke-shape stroke-shape-5"></span>
    <span class="stroke-shape stroke-shape-6"></span>
    <div class="container">
      <div class="row align-items-center">
        <div class="col-lg-9">
          <div class="hero-content">
            <h2 class="section-title pb-2 fs-24 lh-34">Find the best answer to your technical question, <br>
              help others answer theirs
            </h2>
            <p class="lh-26">If you are going to use a passage of Lorem Ipsum, you need to be sure there
              <br> isn't anything embarrassing hidden in the middle of text.
            </p>
            <ul class="generic-list-item pt-3">
              <li><span class="icon-element icon-element-xs shadow-sm d-inline-block me-2"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewBox="0 0 24 24" width="20px" fill="#6c727c"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M11 18h2v-2h-2v2zm1-16C6.48 2 2 6.48 2 12s4.48 10 10 10 10-4.48 10-10S17.52 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm0-14c-2.21 0-4 1.79-4 4h2c0-1.1.9-2 2-2s2 .9 2 2c0 2-3 1.75-3 5h2c0-2.25 3-2.5 3-5 0-2.21-1.79-4-4-4z"/></svg></span> Anybody can ask a question</li>
              <li><span class="icon-element icon-element-xs shadow-sm d-inline-block me-2"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewBox="0 0 24 24" width="20px" fill="#6c727c"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M9 16.2L4.8 12l-1.4 1.4L9 19 21 7l-1.4-1.4L9 16.2z"/></svg></span> Anybody can answer</li>
              <li><span class="icon-element icon-element-xs shadow-sm d-inline-block me-2"><svg xmlns="http://www.w3.org/2000/svg" height="20px" viewBox="0 0 320 512" width="20px"><path fill="#6c727c" d="M41 288h238c21.4 0 32.1 25.9 17 41L177 448c-9.4 9.4-24.6 9.4-33.9 0L24 329c-15.1-15.1-4.4-41 17-41zm255-105L177 64c-9.4-9.4-24.6-9.4-33.9 0L24 183c-15.1 15.1-4.4 41 17 41h238c21.4 0 32.1-25.9 17-41z"></path></svg></span> The best answers are voted up and rise to the top</li>
            </ul>
          </div><!-- end hero-content -->
        </div><!-- end col-lg-9 -->
      </div><!-- end row -->
    </div><!-- end container -->
  </section>
  <!--======================================
          END HERO AREA
  ======================================-->
<% end %>

app/views/posts/partials/_post_user_actions.html.erb
<div class="question-post-user-action">
  <div class="post-menu">
    <div class="btn-group">
      <button class="btn dropdown-toggle after-none" type="button" id="shareDropdownMenu" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Share</button>
      <div class="dropdown-menu dropdown--menu dropdown--menu-2 mt-2" aria-labelledby="shareDropdownMenu">
        <div class="py-3 px-4">
          <h4 class="fs-15 pb-2">Share a link to this question</h4>
          <form action="#" class="copy-to-clipboard">
            <span class="text-success-message">Link Copied!</span>
            <input type="text" class="form-control form--control form-control-sm copy-input" value="<%= post_url(@post) %>">
            <div class="btn-box pt-2 d-flex align-items-center justify-content-between">
              <a href="#" class="btn-text copy-btn">Copy link</a>
              <ul class="social-icons social-icons-sm">
                <li><a href="#" class="bg-8 text-white shadow-none" title="Share link to this question on Facebook"><i class="la la-facebook"></i></a></li>
                <li><a href="#" class="bg-9 text-white shadow-none" title="Share link to this question on Twitter"><i class="la la-twitter"></i></a></li>
                <li><a href="#" class="bg-dark text-white shadow-none" title="Share link to this question on DEV"><i class="lab la-dev"></i></a></li>
              </ul>
            </div>
          </form>
        </div>
      </div>
    </div><!-- btn-group -->
    <% if can? :edit, @post %>
    <%= link_to 'Edit', edit_post_path(@post), class: 'btn', data: { turbo: false } %>
    <% end %>

    <% if can? :destroy, @post %>
    <%= link_to 'Delete', @post, data: { turbo_confirm: 'Are you sure?', "turbo-method": :delete }, class: 'btn' %>
    <% end %>
  </div><!-- end post-menu -->
  <div class="media media-card user-media owner align-items-center">
    <%= link_to profile_users_path(@post.user), class: 'media-img d-block' do %>
      <%= image_tag @post.user.avatar, alt: 'avatar' %>
    <% end %>
    <div class="media-body d-flex flex-wrap align-items-center justify-content-between">
      <div>
        <h5 class="pb-1">
          <%= link_to @post.user.full_name, profile_users_path(@post.user) %>
        </h5>
        <div class="stats fs-12 d-flex align-items-center lh-18">
          <%= user_badge(@post.user) %>
        </div>
      </div>
      <small class="meta d-block text-end">
        <span class="text-black d-block lh-18">asked</span>
        <span class="d-block lh-18 fs-12"><%= time_ago_in_words(@post.created_at) %></span>
      </small>
    </div>
  </div><!-- end media -->
</div><!-- end question-post-user-action -->

app/views/posts/partials/_question_highlight.html.erb
<div class="question-highlight">
  <div class="media media-card shadow-none rounded-0 mb-0 bg-transparent p-0">
    <div class="media-body">
      <h5 class="fs-20">
        <%= @post.title %>
      </h5>
      <div class="meta d-flex flex-wrap align-items-center fs-13 lh-20 py-1">
        <div class="pe-3">
          <span>Asked</span>
          <span class="text-black"><%= time_ago_in_words(@post.created_at) %> ago</span>
        </div>
        <div class="pe-3">
          <span class="pe-1">Active</span>
          <a href="#" class="text-black"><%= last_active(@post) %></a>
        </div>
        <div class="pe-3">
          <span class="pe-1">Viewed</span>
          <span class="text-black"><%= @post.views %> times</span>
        </div>
      </div>
      <div class="tags">
        <% @post.tags&.each do |tag| %>
          <a href="#" class="tag-link"><%= tag %></a>
        <% end %>
      </div>
    </div>
  </div><!-- end media -->
</div><!-- end question-highlight -->

app/views/posts/partials/_related_questions_and_tags.html.erb
<div class="card card-item">
  <div class="card-body">
    <h3 class="fs-17 pb-3">Related Questions</h3>
    <div class="divider"><span></span></div>
    <div class="sidebar-questions pt-3">
      <% related_questions.each do |post| %>
        <div class="media media-card media--card media--card-2">
          <div class="media-body">
            <h5>
              <%= link_to post.title, post_path(post)  %>
            </h5>
            <small class="meta">
              <span class="pe-1"> <%= time_ago_in_words(post.created_at) %> ago</span>
              <span class="pe-1">. by</span>
              <a href="#" class="author"><%= post.user.full_name %></a>
            </small>
          </div>
        </div><!-- end media -->
      <% end %>
    </div><!-- end sidebar-questions -->
  </div>
</div><!-- end card -->
<div class="card card-item">
  <div class="card-body">
    <h3 class="fs-17 pb-3">Trending Tags</h3>
    <div class="divider"><span></span></div>
    <div class="tags pt-4">
      <% trending_tags[0..4].each do |tag| %>
        <div class="tag-item">
          <a href="#" class="tag-link tag-link-md"><%= tag.tag %></a>
          <span class="item-multiplier fs-13"><span>×</span><span><%= tag.total %></span></span>
        </div><!-- end tag-item -->
      <% end %>
      <div class="collapse" id="showMoreTags">
        <% trending_tags[5..-1]&.each do |tag| %>
          <div class="tag-item">
            <a href="#" class="tag-link tag-link-md"><%= tag.tag %></a>
            <span class="item-multiplier fs-13"><span>×</span><span><%= tag.total %></span></span>
          </div><!-- end tag-item -->
        <% end %>
      </div><!-- end collapse -->
      <a class="collapse-btn fs-13" data-bs-toggle="collapse" href="#showMoreTags" role="button" aria-expanded="false" aria-controls="showMoreTags">
        <span class="collapse-btn-hide">Show more<i class="la la-angle-down ms-1 fs-11"></i></span>
        <span class="collapse-btn-show">Show less<i class="la la-angle-up ms-1 fs-11"></i></span>
      </a>
    </div>
  </div>
</div><!-- end card -->

app/views/posts/partials/_subheader.html.erb
<div class="subheader d-flex align-items-center justify-content-between">
  <div class="subheader-title">
    <h3 class="fs-16"><%= pluralize(@post.total_comments, 'Answer') %></h3>
  </div><!-- end subheader-title -->
  <div class="subheader-actions d-flex align-items-center lh-1">
    <label class="fs-13 fw-regular me-1 mb-0">Order by</label>
    <div class="w-100px">
<!--      <select class="select-container">-->
<!--        <option value="active">active</option>-->
<!--        <option value="oldest">oldest</option>-->
<!--        <option value="votes" selected="selected">votes</option>-->
<!--      </select>-->

      <%= content_tag(:select, class: 'select-container', id: 'sort-by') do %>
        <% PostsController::SORT_BY_OPTIONS.each do |key, value| %>
          <% selected = (params[:sort_by] == key || key ==  PagesController::SORT_BY_OPTIONS.keys.first) ? { selected: true } : {} %>
          <%= content_tag(:option, key, value: key, **selected ) %>
        <% end %>
      <% end %>

    </div>
  </div><!-- end subheader-actions -->
</div><!-- end subheader -->

app/views/posts/partials/_votes.html.erb
<div class="votes votes-styled w-auto">
  <%#= turbo_frame_tag @post do %>
    <div id="vote" class="upvotejs">
      <%= link_to '', toggle_upvote_post_votes_path(@post), data: { 'turbo-method': :patch }, class: "upvote #{@post.upvoted?(current_user) ? 'upvote-on' : ''}", 'data-bs-toggle': 'tooltip', 'data-placement': 'right', title: 'This question is useful' %>
      <span class="count"><%= @post.total_votes %></span>
      <%= link_to '', toggle_downvote_post_votes_path(@post), data: { 'turbo-method': :patch }, class: "downvote #{@post.downvoted?(current_user) ? 'downvote-on' : ''}", 'data-bs-toggle': 'tooltip', 'data-placement': 'right', title: 'This question is not useful' %>
<!--      <a class="star" data-bs-toggle="tooltip" data-placement="right" title="Bookmark this question."></a>-->
    </div>
  <%# end %>
</div><!-- end votes -->