config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
  devise_for :users, module: :users

  resources :users, only: [] do
    collection do
      get 'profile(/:user_id)', to: 'users#profile', as: :profile
    end
  end
  resources :categories
  resources :posts do
    member do
      patch 'mark_as_accepted_comment/:comment_id', to: "posts#mark_as_accepted_comment", as: :mark_as_accepted
    end
    resources :comments
    resources :votes, only: [] do
      collection do
        patch 'toggle_upvote'
        patch 'toggle_downvote'
      end
    end
  end

  resources :comments, only: [] do
    resources :votes, only: [] do
      collection do
        patch 'toggle_upvote'
        patch 'toggle_downvote'
      end
    end
  end

  resources :notifications, only: %i[index destroy] do
    member do
      get 'mark_as_read'
    end
  end

  resources :supports

  post '/', to: 'pages#home'

  get 'user_policies', to: 'pages#user_policies', as: :user_policies
  get 'faq', to: 'pages#faq', as: :faq
  get 'support_page', to: 'pages#support_page', as: :support_page
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<!-- ================================
         END FOOTER AREA
================================= -->
<section class="footer-area pt-80px position-relative border-top border-top-gray bg-white" style="box-shadow: 0 1rem 2.1rem rgba(0, 0, 0, 0.175) !important;">
  <span class="vertical-bar-shape vertical-bar-shape-1"></span>
  <span class="vertical-bar-shape vertical-bar-shape-2"></span>
  <span class="vertical-bar-shape vertical-bar-shape-3"></span>
  <span class="vertical-bar-shape vertical-bar-shape-4"></span>
  <div class="container">
    <div class="row">
      <div class="col-lg-3 responsive-column-half">
        <div class="footer-item">
          <a href="index.html" class="d-inline-block" style="color: #26D8B2; font-weight: 900;">
            <%= image_tag 'app_logo.png', alt: 'footer logo', class: 'footer-logo', height: 48 %>
            <%= t('app_name') %>
          </a>
          <p class="py-3 fs-15 lh-24">
            The <%= t('app_name') %> is a dynamic web application designed to foster collaboration, discussion, and knowledge sharing among students.
          </p>
          <div class="social-icon-box">
            <a class="me-1 icon-element icon-element-sm shadow-sm text-gray hover-y d-inline-block" href="https://github.com/froidautaj/froidautaj" target="_blank" title="Follow on Facebook">
              <svg focusable="false" class="svg-inline--fa fa-facebook-f fa-w-10" width="16px" height="16px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512"><path fill="currentColor" d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z"></path></svg>
            </a>
            <a class="me-1 icon-element icon-element-sm shadow-sm text-gray hover-y d-inline-block" href="https://github.com/froidautaj/froidautaj" target="_blank" title="Follow on Twitter">
              <svg focusable="false" class="svg-inline--fa fa-twitter fa-w-16" width="16px" height="16px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><path fill="currentColor" d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z"></path></svg>
            </a>
            <a class="me-1 icon-element icon-element-sm shadow-sm text-gray hover-y d-inline-block" href="https://github.com/froidautaj/froidautaj" target="_blank" title="Follow on Linkedin">
              <svg focusable="false" class="svg-inline--fa fa-linkedin fa-w-14" width="16px" height="16px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M416 32H31.9C14.3 32 0 46.5 0 64.3v383.4C0 465.5 14.3 480 31.9 480H416c17.6 0 32-14.5 32-32.3V64.3c0-17.8-14.4-32.3-32-32.3zM135.4 416H69V202.2h66.5V416zm-33.2-243c-21.3 0-38.5-17.3-38.5-38.5S80.9 96 102.2 96c21.2 0 38.5 17.3 38.5 38.5 0 21.3-17.2 38.5-38.5 38.5zm282.1 243h-66.4V312c0-24.8-.5-56.7-34.5-56.7-34.6 0-39.9 27-39.9 54.9V416h-66.4V202.2h63.7v29.2h.9c8.9-16.8 30.6-34.5 62.9-34.5 67.2 0 79.7 44.3 79.7 101.9V416z"></path></svg>
            </a>
            <a class="me-1 icon-element icon-element-sm shadow-sm text-gray hover-y d-inline-block" href="https://github.com/froidautaj/froidautaj" target="_blank" title="Follow on Instagram">
              <svg focusable="false" class="svg-inline--fa fa-instagram-square fa-w-14" width="16px" height="16px" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512"><path fill="currentColor" d="M224,202.66A53.34,53.34,0,1,0,277.36,256,53.38,53.38,0,0,0,224,202.66Zm124.71-41a54,54,0,0,0-30.41-30.41c-21-8.29-71-6.43-94.3-6.43s-73.25-1.93-94.31,6.43a54,54,0,0,0-30.41,30.41c-8.28,21-6.43,71.05-6.43,94.33S91,329.26,99.32,350.33a54,54,0,0,0,30.41,30.41c21,8.29,71,6.43,94.31,6.43s73.24,1.93,94.3-6.43a54,54,0,0,0,30.41-30.41c8.35-21,6.43-71.05,6.43-94.33S357.1,182.74,348.75,161.67ZM224,338a82,82,0,1,1,82-82A81.9,81.9,0,0,1,224,338Zm85.38-148.3a19.14,19.14,0,1,1,19.13-19.14A19.1,19.1,0,0,1,309.42,189.74ZM400,32H48A48,48,0,0,0,0,80V432a48,48,0,0,0,48,48H400a48,48,0,0,0,48-48V80A48,48,0,0,0,400,32ZM382.88,322c-1.29,25.63-7.14,48.34-25.85,67s-41.4,24.63-67,25.85c-26.41,1.49-105.59,1.49-132,0-25.63-1.29-48.26-7.15-67-25.85s-24.63-41.42-25.85-67c-1.49-26.42-1.49-105.61,0-132,1.29-25.63,7.07-48.34,25.85-67s41.47-24.56,67-25.78c26.41-1.49,105.59-1.49,132,0,25.63,1.29,48.33,7.15,67,25.85s24.63,41.42,25.85,67.05C384.37,216.44,384.37,295.56,382.88,322Z"></path></svg>
            </a>
          </div>
        </div><!-- end footer-item -->
      </div><!-- end col-lg-3 -->
      <div class="col-lg-3 responsive-column-half">
        <div class="footer-item">
          <h3 class="fs-18 fw-bold pb-2">User Policies</h3>
          <ul class="generic-list-item generic-list-item-hover-underline pt-3">
            <li><%= link_to 'Privacy Policy', user_policies_path %></li>
            <li><%= link_to 'Terms of Service', user_policies_path %></li>
            <li><%= link_to 'Cookie Policy', user_policies_path %></li>
          </ul>
        </div><!-- end footer-item -->
      </div><!-- end col-lg-3 -->
      <div class="col-lg-3 responsive-column-half">
        <div class="footer-item">
          <h3 class="fs-18 fw-bold pb-2">Help</h3>
          <ul class="generic-list-item generic-list-item-hover-underline pt-3">
            <li><%= link_to 'Knowledge Base', faq_path %></li>
            <li><%= link_to 'Support', support_page_path %></li>
          </ul>
        </div><!-- end footer-item -->
      </div><!-- end col-lg-3 -->
    </div><!-- end row -->
  </div><!-- end container -->
  <hr class="border-top-gray my-4">
  <div class="container">
    <div class="row align-items-center pb-4 copyright-wrap">
      <div class="col-lg-6">
      </div><!-- end col-lg-6 -->
    </div><!-- end row -->
  </div><!-- end container -->
</section><!-- end footer-area -->
<!-- ================================
          END FOOTER AREA
================================= -->



<!-- start back to top -->
<div id="back-to-top" data-bs-toggle="tooltip" data-placement="top" title="Return to top">
  <i class="la la-arrow-up"></i>
</div>
<!-- end back to top -->

app/views/shared/_navbar.html.erb
<!--======================================
        START HEADER AREA
    ======================================-->
<header class="header-area bg-white border-bottom border-bottom-gray shadow-sm">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-2">
        <div class="logo-box">
          <%= link_to  root_path, class: 'logo', data: { turbo: false }, style: 'color: #26D8B2; font-weight: 900;' do %>
            <%= image_tag 'app_logo.png', alt: 'logo', height: '48' %>
            <%= t('app_name') %>
          <% end %>
          <div class="user-action">
            <div class="search-menu-toggle icon-element icon-element-xs shadow-sm me-1" data-bs-toggle="tooltip" data-placement="top" title="Search">
              <i class="la la-search"></i>
            </div>
            <% unless user_signed_in? %>
            <div class="off-canvas-menu-toggle icon-element icon-element-xs shadow-sm me-1" data-bs-toggle="tooltip" data-placement="top" title="Main menu">
              <i class="la la-bars"></i>
            </div>
            <% else %>
            <div class="user-off-canvas-menu-toggle icon-element icon-element-xs shadow-sm" data-bs-toggle="tooltip" data-placement="top" title="User menu">
              <i class="la la-user"></i>
            </div>
            <% end %>
          </div>
        </div>
      </div><!-- end col-lg-2 -->
      <div class="col-lg-10">
        <div class="menu-wrapper border-left border-left-gray ps-4 justify-content-end">
          <nav class="menu-bar me-auto">
            <ul>
              <li class="is-mega-menu">
                <%= link_to 'Home', root_path, data: { turbo: false }%>
              </li>
              <li>
                <%= link_to 'Ask a question', new_post_path, data: { turbo: false } %>
              </li>
              <% if user_signed_in? && current_user.is_a?(SuperUser) %>
                <li>
                  <%= link_to 'Support', supports_path, data: { turbo: false } %>
                </li>
              <% end %>
            </ul><!-- end ul -->
          </nav><!-- end main-menu -->
          <%= simple_form_for('', url: root_path, html: { class: 'me-4' }, data: { turbo: false }) do |f| %>
            <div class="form-group mb-0">
              <%= f.input :query, label: false, wrapper: false, input_html: { class: 'form-control form--control form--control-bg-gray', placeholder: 'Type your search words...' } %>
              <%= button_tag type: 'submit', class: "form-btn" do %>
                <i class="la la-search"></i>
              <% end %>
            </div>
          <% end %>
          <div class="nav-right-button">
            <% if user_signed_in? %>
              <ul class="user-action-wrap d-flex align-items-center">
                <li class="dropdown">
                  <% if current_user.notifications.where(read: false).any? %>
                    <span class="ball red ball-lg noti-dot"></span>
                  <% end %>
                  <a class="nav-link dropdown-toggle dropdown--toggle" href="#" id="notificationDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="la la-bell"></i>
                  </a>
                  <div class="dropdown-menu dropdown--menu dropdown-menu-right mt-3 keep-open" aria-labelledby="notificationDropdown">
                    <h6 class="dropdown-header"><i class="la la-bell pe-1 fs-16"></i>Notifications</h6>
                    <div class="dropdown-divider border-top-gray mb-0"></div>
                    <div class="dropdown-item-list">
                      <%= notifications_list %>
                    </div>
                    <% if can? :destroy, Notification %>
                      <%= link_to notifications_path, class: 'dropdown-item pb-1 border-bottom-0 text-center btn-text fw-regular' do %>
                        View All Notifications <i class="la la-arrow-right icon ms-1"></i>
                      <% end %>
                    <% end %>
                  </div>
                </li>
                <li class="dropdown user-dropdown">
                  <a class="nav-link dropdown-toggle dropdown--toggle ps-2" href="#" id="userMenuDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <div class="media media-card media--card shadow-none mb-0 rounded-0 align-items-center bg-transparent">
                      <div class="media-img media-img-xs flex-shrink-0 rounded-full me-2">
                        <%= image_tag current_user.avatar, alt: 'avatar', class: 'rounded-full' %>
                      </div>
                      <div class="media-body p-0 border-left-0">
                        <h5 class="fs-14"><%= current_user.full_name %></h5>
                      </div>
                    </div>
                  </a>
                  <div class="dropdown-menu dropdown--menu dropdown-menu-right mt-3 keep-open" aria-labelledby="userMenuDropdown">
                    <h6 class="dropdown-header">Hi, <%= current_user.full_name %></h6>
                    <div class="dropdown-divider border-top-gray mb-0"></div>
                    <div class="dropdown-item-list">
                      <%= link_to profile_users_path, class: 'dropdown-item' do %>
                        <i class="la la-user me-2"></i>Profile
                      <% end %>
                      <%= button_to destroy_user_session_path, class: 'dropdown-item', method: :delete do %>
                        <i class="la la-power-off me-2"></i>Log out
                      <% end %>
                    </div>
                  </div>
                </li>
              </ul>
              <%# end %>
            <% else %>
              <%= link_to new_user_session_path, class: 'btn theme-btn theme-btn-outline me-2', data: { turbo: false } do %>
                <i class="la la-sign-in me-1"></i> Login
               <% end %>
              <%= link_to new_user_registration_path, class: 'btn theme-btn' do %>
                <i class="la la-user me-1"></i> Sign up
              <% end %>
            <% end %>
          </div><!-- end nav-right-button -->
        </div><!-- end menu-wrapper -->
      </div><!-- end col-lg-10 -->
    </div><!-- end row -->
  </div><!-- end container -->
  <div class="off-canvas-menu custom-scrollbar-styled">
    <div class="off-canvas-menu-close icon-element icon-element-sm shadow-sm" data-bs-toggle="tooltip" data-placement="left" title="Close menu">
      <i class="la la-times"></i>
    </div><!-- end off-canvas-menu-close -->
    <ul class="generic-list-item off-canvas-menu-list pt-90px">
      <li class="is-mega-menu">
        <%= link_to 'Home', root_path %>
      </li>
      <li>
        <%= link_to 'Ask a question', new_post_path, data: { turbo: false } %>
      </li>
    </ul>
    <div class="off-canvas-btn-box px-4 pt-5 text-center">
      <% unless user_signed_in? %>
      <%= link_to new_user_session_path, class: 'btn theme-btn theme-btn-sm theme-btn-outline' do %>
        <i class="la la-sign-in me-1"></i> Login
      <% end %>
      <span class="fs-15 fw-medium d-inline-block mx-2">Or</span>
      <%= link_to new_user_registration_path, class: 'btn theme-btn theme-btn-sm' do %>
        <i class="la la-user me-1"></i> Sign up
      <% end %>
    <% end %>
    </div>
  </div><!-- end off-canvas-menu -->
  <div class="user-off-canvas-menu custom-scrollbar-styled">
    <div class="user-off-canvas-menu-close icon-element icon-element-sm shadow-sm" data-bs-toggle="tooltip" data-placement="left" title="Close menu">
      <i class="la la-times"></i>
    </div><!-- end user-off-canvas-menu-close -->
    <ul class="nav nav-tabs generic-tabs generic--tabs pt-90px ps-4 shadow-sm" id="myTab2" role="tablist">
      <li class="nav-item"><div class="anim-bar"></div></li>
      <li class="nav-item">
        <a class="nav-link active" id="user-profile-menu-tab" data-bs-toggle="tab" href="#user-profile-menu" role="tab" aria-controls="user-profile-menu" aria-selected="true">Profile</a>
      </li>
    </ul>
    <div class="tab-content pt-3" id="myTabContent2">
      <div class="tab-pane fade show active" id="user-profile-menu" role="tabpanel" aria-labelledby="user-profile-menu-tab">
        <div class="dropdown--menu shadow-none w-auto rounded-0">
          <div class="dropdown-item-list">
            <%= link_to profile_users_path, class: 'dropdown-item' do %>
              <i class="la la-user me-2"></i>Profile
            <% end %>
            <%= button_to destroy_user_session_path, class: 'dropdown-item', method: :delete do %>
              <i class="la la-power-off me-2"></i>Log out
            <% end %>
          </div>
        </div>
      </div><!-- end tab-pane -->
    </div>
  </div><!-- end user-off-canvas-menu -->
  <div class="mobile-search-form">
    <div class="d-flex align-items-center">
      <form method="post" class="flex-grow-1 me-3">
        <div class="form-group mb-0">
          <input class="form-control form--control pl-40px" type="text" name="search" placeholder="Type your search words...">
          <span class="la la-search input-icon"></span>
        </div>
      </form>
      <div class="search-bar-close icon-element icon-element-sm shadow-sm">
        <i class="la la-times"></i>
      </div><!-- end off-canvas-menu-close -->
    </div>
  </div><!-- end mobile-search-form -->
  <div class="body-overlay"></div>
</header><!-- end header-area -->
<!--======================================
        END HEADER AREA
======================================-->