config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root 'pages#home'
  devise_for :users, module: :users

  resources :users, only: [] do
    collection do
      get 'profile(/:user_id)', to: 'users#profile', as: :profile
    end
  end
  resources :categories
  resources :posts do
    member do
      patch 'mark_as_accepted_comment/:comment_id', to: "posts#mark_as_accepted_comment", as: :mark_as_accepted
    end
    resources :comments
    resources :votes, only: [] do
      collection do
        patch 'toggle_upvote'
        patch 'toggle_downvote'
      end
    end
  end

  resources :comments, only: [] do
    resources :votes, only: [] do
      collection do
        patch 'toggle_upvote'
        patch 'toggle_downvote'
      end
    end
  end

  resources :notifications, only: %i[index destroy] do
    member do
      get 'mark_as_read'
    end
  end

  resources :supports

  post '/', to: 'pages#home'

  get 'user_policies', to: 'pages#user_policies', as: :user_policies
  get 'faq', to: 'pages#faq', as: :faq
  get 'support_page', to: 'pages#support_page', as: :support_page
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :posts, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  #     1. Psychological: <i class="las la-brain"></i>
  #     2. Nutrition: <i class="las la-apple-alt"></i>
  #     3. Exercise: <i class="las la-running"></i>
  #     4. Social Support: <i class="las la-users"></i>
  #     5. Academic Well-Being: <i class="las la-school"></i>
  #     6. Stress Management: <i class="las la-heartbeat"></i>

  CATEGORY_ICON_MAP = {
    'Psychological' => 'las la-brain',
    'Nutrition' => 'las la-apple-alt',
    'Exercise' => 'las la-running',
    'Social Support' => 'las la-users',
    'Academic Well-Being' => 'las la-school',
    'Stress Management' => 'las la-heartbeat',
  }.freeze

  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.joins(:posts)
                          .select('categories.id, categories.name, count(posts.id) as posts_count')
                          .group('categories.id')
  end

  # GET /categories/1 or /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.require(:category).permit(:name, :description)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p>
    <strong>Name:</strong>
    <%= category.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= category.description %>
  </p>

</div>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<!-- ================================
         START QUESTION AREA
================================= -->
<section class="question-area pt-40px pb-40px">
  <div class="container">
    <div class="filters pb-3">
      <div class="d-flex flex-wrap align-items-center justify-content-between pb-3">
        <h3 class="fs-22 fw-medium">Categories</h3>
        <%= link_to 'Ask Question', new_post_path, class: 'btn theme-btn theme-btn-sm'  %>
      </div>
    </div><!-- end filters -->
    <div class="row">
      <% @categories.each do |category| %>
      <div class="col-lg-3 responsive-column-half">
        <div class="media media-card p-3 align-items-center hover-y">
          <div class="icon-element shadow-sm flex-shrink-0 me-3 border border-gray">
            <i class="<%= CategoriesController::CATEGORY_ICON_MAP[category.name] %>" style="font-size: 43px; padding-top: 7px;"></i>
          </div>
          <div class="media-body">
            <h5 class="fs-19 fw-medium mb-1">
              <%= link_to category.name, root_path(category_id: category.id) %>
            </h5>
            <p class="fw-medium fs-15 text-black-50 lh-18"><%= category.posts_count %></p>
          </div><!-- end media-body -->
        </div><!-- end media -->
      </div><!-- end col-lg-3 -->
      <% end %>
    </div><!-- end row -->
  </div><!-- end container -->
</section><!-- end question-area -->
<!-- ================================
         END QUESTION AREA
================================= -->

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>